fedimint/ecash-app

rust/carbine_fedimint/build.sh
scripts/build-android.sh
scripts/build-arm-android.sh
scripts/build-linux.sh

Using `#!/usr/bin/env bash` will look for the first instance of `bash` in `$PATH`, which makes these scripts more portable and uses `bash` defined in the `devShell`.

fix: use bash defined in PATH in shebangs

---

lib/dashboard.dart
lib/discover.dart
lib/ecash_send.dart
lib/fed_preview.dart
lib/main.dart
lib/pay_preview.dart
lib/payment_selector.dart
lib/request.dart
lib/scan.dart
lib/send.dart
lib/setttings.dart
lib/sidebar.dart
lib/success.dart
lib/theme.dart
lib/welcome.dart

This change runs `dart format` on all `.dart` files except `lib/number_pad.dart` to avoid conflicts with https://github.com/fedimint/fedimint-app/pull/11.

chore: format all dart files with `dart format`

---

lib/ecash_send.dart
lib/frb_generated.dart
lib/lib.dart
lib/number_pad.dart
lib/redeem_ecash.dart
lib/scan.dart
lib/theme.dart
rust/carbine_fedimint/src/frb_generated.rs
rust/carbine_fedimint/src/lib.rs

Adds a screen to redeem ecash from a string.
Commit was done before `dart format` commit hook, but I ran it manually so hopefully its still in line. If not, this will be the last PR where it has formatting issues

feat: add redeem ecash screen

---

lib/ecash_send.dart
lib/main.dart
lib/utils.dart

@m1sterc001guy had a good suggestion that we should create a function for our msats -> sats conversions. Dart supports simple [extension methods](https://dart.dev/language/extension-methods), however we can also introduce a pure function if that's more clear.

refactor: introduce toSats extension for BigInt

---

lib/main.dart

I'm a fan of the msats formatting that substitutes "," for spaces. This unifies the sats format on the dashboard to have the same formatting.
**Before**
**After**

fix: unify sats and msats formatting

---

lib/scan.dart
rust/carbine_fedimint/src/lib.rs
rust/carbine_fedimint/src/multimint.rs

Found an interesting bug due to the new subscription mechanism. Because it returns a stream, it actually holds onto the `RwLock` that we have over `Multimint`. This will block any operation that requires a write lock on `Multimint`.
The fix is to remove the `RwLock` over `Multimint`. It is not necessary, we already have a `RwLock` over `clients` inside of `Multimint` and everything else should be clonable. I think this makes the code simpler.

fix: deadlock in recovery

---

lib/widgets/transactions_list.dart

If we don't schedule the scroll controller until after the build finishes, we get the following error
```
══╡ EXCEPTION CAUGHT BY WIDGET LIBRARY ╞════════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for
ScrollNotificationObserverState:
setState() or markNeedsBuild() called during build.
This AppBar widget cannot be marked as needing to build because the framework is already in the
process of building widgets. A widget can be marked as needing to be built during the build phase
only if one of its ancestors is currently building. This exception is allowed because the framework
builds parent widgets before children, which means a dirty descendant will always be built.
Otherwise, the framework might not visit this …
```

fix: wait for build to finish before changing scroll position

---

lib/ln_address.dart
lib/setttings.dart

Lightning Address isn't quite ready yet, but I wanted to merge it to avoid conflicts moving forward. For now we will just comment out the Settings option, so we can re-enable it when ready.

fix: change defaults and turn off lightning address

---

.github/workflows/android-release.yml

Will require the following secrets to be set first:
* `ANDROID_KEYSTORE`
* `KEYSTORE_PASSWORD`
* `KEY_PASSWORD`
* `KEY_ALIAS`
I can use the testing key I used so far or @m1sterc001guy or @bradleystachurski can generate one. I don't mind too much, let's just back it up properly :smile: 
See this CI run as an example (without the hash suffix in the APK name yet and still called puncture, I fixed that afterwards for this PR): https://github.com/elsirion/fedimint-app/actions/runs/16388717670/job/46311840212

feat: build APK in CI

---

lib/fed_preview.dart
lib/frb_generated.dart
lib/lib.dart
lib/number_pad.dart
lib/request.dart
rust/carbine_fedimint/src/frb_generated.rs
rust/carbine_fedimint/src/lib.rs

Working towards: https://github.com/fedimint/fedimint-app/issues/43
- Makes `wallet_exists` panic instead of return result
- Removes `await_ecash_send`, we don't use it anywhere
- Adds try/catch around `selectReceiveGateway` and `receive`
- Adds try/catch around `awaitReceive`
- Adds try/catch around `walletSummary`

fix: add more try catches and remove unused functions

---

rust/ecashapp/src/multimint.rs

Fixes: https://github.com/fedimint/fedimint-app/issues/136
Changes caching interval to 30 secs. Price caching interval is now 5 mins

chore: update cache interval to 30 secs

---

lib/app.dart
lib/frb_generated.dart
lib/multimint.dart
lib/multimint.freezed.dart
lib/scan.dart
lib/screens/dashboard.dart
rust/ecashapp/src/frb_generated.rs
rust/ecashapp/src/multimint.rs

During recovery, while joining the federations, it is a bit confusing what is happening. This PR changes the UI to add a status message and a nice toast when successfully re-joining a federation.

feat: add recovery status message

---

lib/splash.dart

Fixes: https://github.com/fedimint/e-cash-app/issues/139
We don't need to delay the splash screen, otherwise ours and Flutter's are both shown which is a bit awkward.

fix: remove splash delay

---

lib/db.dart
lib/setttings.dart
lib/utils.dart
rust/ecashapp/src/db.rs
rust/ecashapp/src/frb_generated.rs

Fixes: https://github.com/fedimint/e-cash-app/issues/138
Given that our icon is the sat symbol we might as well support the Display setting to use the sat symbol. I hate that there's no one sat symbol :/

feat: add sat symbol

---

lib/fed_preview.dart
lib/ln_address.dart

Changing default recurringd and ln address server to `ecash.love`. Can still be set in the meta.

feat: change ln address domain to ecash.love

---

lib/fed_preview.dart
rust/ecashapp/src/multimint.rs

Fixes: https://github.com/fedimint/e-cash-app/issues/158
They are cached and updated every 30 seconds, so there will be a small lag between the guardian going down and it being detected in the UI.
The caching logic did not work when guardians were down. This is fixed in this PR.

fix: Online Status works properly

---

lib/frb_generated.dart
lib/multimint.dart
lib/widgets/transactions_list.dart
pubspec.lock
rust/ecashapp/src/frb_generated.rs
rust/ecashapp/src/multimint.rs

In the UI, we track pending deposits grouped by txid. This is not correct, since it's possible for the deposit transaction to have multiple outputs going to the same deposit address. The fix is simply grouping by outpoint instead of txid.

fix: use tx outpoint instead of txid

---

.github/actions/android-build/action.yml

Fixes: https://github.com/fedimint/e-cash-app/issues/201
As far as I can tell, the rest of our build process is already `arm64` specific.

chore: remove rust targets that are not arm64

---

pubspec.yaml
rust/ecashapp/Cargo.lock
rust/ecashapp/Cargo.toml

We released `v0.1.0` so we can bump the version on master. Using the same convention as we do in `fedimint/fedimint` with the `-alpha` suffix.

chore: bump version to v0.2.0-alpha

---

.github/workflows/android-debug.yml

In order to add our android debug workflow as a required step, we need to have the workflow complete a run vs `master`. Adding the dispatch will allow us to trigger the workflow, then we can add it as a required step in PRs.

chore: add workflow dispatch to android debug workflow

---

lib/discover.dart
lib/fed_preview.dart
lib/number_pad.dart
lib/scan.dart
lib/screens/dashboard.dart
lib/setttings.dart
lib/sidebar.dart
lib/theme.dart
lib/widgets/gateways.dart
lib/widgets/transaction_details.dart
lib/widgets/transaction_item.dart

There are some spots in our code where "something happens" then we want to show a bottom modal sheet. Sometimes this happens when pressing a button or scanning a QR code. 
We ideally want the bottom modal sheet to be as responsive as possible, since it gives users an indication that something happened. In certain instances, we need to call an async function (i.e to get federation meta and display to user), and this sometimes takes time.
This refactor changes our bottom modal sheet to take an async function instead of just a child widget. So when the async function is executing, the bottom modal sheet is displayed with a spinner. When it is finished, the returned child widget is then shown to the user. 
Makes the app feel snappier.

refactor: bottom modal sheet takes async function
