fedimint/ecash-app

lib/frb_generated.dart
lib/lib.dart
lib/pay_preview.dart
lib/request.dart
lib/scan.dart
lib/theme.dart
rust/carbine_fedimint/src/frb_generated.rs
rust/carbine_fedimint/src/lib.rs

Unifies it with the receive workflow

feat: improve LN send payment experience

---

lib/db.dart
lib/frb_generated.dart
lib/lib.dart
lib/mnemonic.dart
lib/setttings.dart
rust/carbine_fedimint/src/db.rs
rust/carbine_fedimint/src/frb_generated.rs
rust/carbine_fedimint/src/lib.rs

Adds a widget for displaying your recovery phrase

feat: add mnemonic widget

---

rust/carbine_fedimint/src/lib.rs

Fixes: https://github.com/fedimint/fedimint-app/issues/22
Adds a basic unit test for verifying LNv2 send and receive amounts

test: add unit tests for lnv2 send and receive amounts

---

lib/dashboard.dart
rust/carbine_fedimint/src/multimint.rs

Re: https://github.com/fedimint/fedimint-app/pull/30#discussion_r2132365938

On-chain deposit followups

---

rust/carbine_fedimint/src/multimint.rs

Fixes: https://github.com/fedimint/fedimint-app/issues/73

chore: verify that a user cannot join a federation that they have already joined

---

lib/app.dart
lib/create_wallet.dart
lib/fed_preview.dart
lib/frb_generated.dart
lib/frb_generated.io.dart
lib/frb_generated.web.dart
lib/lib.dart
lib/multimint.dart
lib/multimint.freezed.dart
lib/nostr.dart
lib/recovery_progress.dart
lib/screens/dashboard.dart
lib/splash.dart
lib/utils.dart
rust/carbine_fedimint/src/frb_generated.rs
rust/carbine_fedimint/src/lib.rs
rust/carbine_fedimint/src/multimint.rs
rust/carbine_fedimint/src/nostr.rs

Closes: https://github.com/fedimint/fedimint-app/issues/33
Closes: https://github.com/fedimint/fedimint-app/issues/34
Backs up federation invite codes to Nostr and retrieves them when recovering.
Also updates the recovery UI to show the progress of each module.

feat: backup/recovery from Nostr and progress bar

---

lib/app.dart
lib/setttings.dart
lib/welcome.dart

Fixes: https://github.com/fedimint/fedimint-app/issues/90
Small improvements, we can always tweak if we don't like them

feat: add Fedimint explainer screen

---

lib/frb_generated.dart
lib/lib.dart
lib/lib.freezed.dart
lib/number_pad.dart
lib/scan.dart
lib/screens/dashboard.dart
lib/utils.dart
rust/carbine_fedimint/src/frb_generated.rs
rust/carbine_fedimint/src/lib.rs

Fixes: https://github.com/fedimint/fedimint-app/issues/97
Allows us to scan a Bitcoin address without an amount.

feat: scan a bitcoin address without an amount

---

lib/app.dart
lib/frb_generated.dart
lib/frb_generated.io.dart
lib/frb_generated.web.dart
lib/lib.dart
lib/multimint.dart
lib/multimint.freezed.dart
lib/redeem_ecash.dart
lib/scan.dart
lib/screens/dashboard.dart
lib/toast.dart
rust/carbine_fedimint/src/frb_generated.rs
rust/carbine_fedimint/src/lib.rs
rust/carbine_fedimint/src/multimint.rs

Fixes: https://github.com/fedimint/fedimint-app/issues/100
Allows the user to redeem the ecash when they're back online. Also adds a toast for received ecash.

feat: offline ecash redeem

---

lib/frb_generated.dart
lib/frb_generated.io.dart
lib/frb_generated.web.dart
lib/lib.dart
lib/multimint.dart
lib/screens/dashboard.dart
lib/widgets/gateway_details.dart
lib/widgets/gateways.dart
rust/carbine_fedimint/src/frb_generated.rs
rust/carbine_fedimint/src/lib.rs
rust/carbine_fedimint/src/multimint.rs

Fixes: https://github.com/fedimint/fedimint-app/issues/62
LNv2 implementation isn't perfect, but it will display one gateway which is good enough IMO. Will need Fedimint changes to make it better.

feat: List Gateways Tab

---

lib/app.dart
lib/create_wallet.dart
lib/discover.dart
lib/ecash_send.dart
lib/number_pad.dart
lib/onchain_receive.dart
lib/onchain_send.dart
lib/request.dart
lib/scan.dart
lib/send.dart
lib/toast.dart
lib/widgets/addresses.dart
lib/widgets/transaction_details.dart

Fixes: https://github.com/fedimint/fedimint-app/issues/113

fix: removing all snackbars, replacing with our own toast

---

lib/app.dart
lib/payment_selector.dart
lib/scan.dart
lib/screens/dashboard.dart

Fixes: https://github.com/fedimint/fedimint-app/issues/95

fix: return to dashboard after action from scan

---

lib/ln_address.dart
rust/carbine_fedimint/src/multimint.rs

Fixes: https://github.com/fedimint/fedimint-app/issues/133

fix: use delete instead of post and add spinner

---

lib/fed_preview.dart
lib/theme.dart

Fixing some leftover `greenAccent` colors

chore: update left over greenAccent colors

---

lib/discover.dart
lib/scan.dart
rust/ecashapp/src/multimint.rs

Fixes: https://github.com/fedimint/e-cash-app/issues/43
All of our function calls into rust should now have a try/catch around them. We can open new issues for any that I missed.

chore: handle remaining potential failures that can happen in scan

---

lib/frb_generated.dart
lib/ln_address.dart
lib/multimint.dart
rust/ecashapp/src/frb_generated.rs
rust/ecashapp/src/multimint.rs

Fixes: https://github.com/fedimint/e-cash-app/issues/137
Tested using devimint federation and setting it to localhost

feat: get recurringd from meta

---

lib/app.dart
lib/frb_generated.dart
lib/lib.dart
lib/nostr.dart
lib/relays.dart
lib/seed_input.dart
lib/utils.dart
rust/ecashapp/src/frb_generated.rs
rust/ecashapp/src/lib.rs
rust/ecashapp/src/nostr.rs

Fixes: https://github.com/fedimint/e-cash-app/issues/130

feat: custom Nostr relay while recovering

---

.github/workflows/android-release.yml

Fixes: https://github.com/fedimint/e-cash-app/issues/154
Trying to get versioned builds in CI

chore: versioned builds

---

.github/workflows/android-release.yml

Environment variables are not interpolating, using outputs instead

fix: ci not interpolating enviroment variables

---

lib/fed_preview.dart

Adding a health bar that tries to visual the federation's threshold

feat: Add Health Bar

---

lib/ln_address.dart

We currently have a bug that prevents The E-Cash App from changing the Lightning Address server. This PR fixes that.

fix: can change LN Address server

---

lib/fed_preview.dart

Fixes a few bugs I found when leaving/joining federations:
- There is no spinner when pressing Confirm, allowing the user to press the button multiple times which causes problems
- The Nostr backup of the federations isn't updated on leaving, meaning the user would re-join federations that they left on recovery
- The `pop` logic was brittle and would sometimes leave the user in a screen where they cannot navigate.
These are all fixed with this PR

fix: leave federation bugs

---

lib/ecash_send.dart
lib/redeem_ecash.dart
lib/screens/dashboard.dart
lib/widgets/transaction_details.dart
lib/widgets/transaction_item.dart
lib/widgets/transactions_list.dart
linux/runner/my_application.cc

In user facing spots of the app, I think we should use "E-Cash".
I think I got everywhere, but it is difficult to write a good `grep` command to find all, lots of false positives.

chore: use E-Cash in user facing spots of the app

---

android/app/build.gradle.kts
android/app/src/main/kotlin/app/ecash/MainActivity.kt
linux/CMakeLists.txt
pubspec.lock

The release branch will have it set to `org.fedimint.app`

chore: change package ID to org.fedimint.app.master

---

lib/screens/dashboard.dart
lib/widgets/addresses.dart
lib/widgets/dashboard_balance.dart
lib/widgets/dashboard_header.dart
lib/widgets/gateway_details.dart
lib/widgets/gateways.dart
lib/widgets/ln_address_dialog.dart
lib/widgets/note_summary.dart
lib/widgets/pending_deposit_item.dart
scripts/git-hooks/pre-commit.sh

We have a pre-commit hook that verifies dart files are formatted, but it wasn't recursively formatting dart files.

fix: recursively format dart files in pre-commit hook

---

.github/actions/android-build/action.yml
.github/workflows/android-release.yml

Backport of https://github.com/fedimint/e-cash-app/pull/196

[Backport] chore: conditionally set package id for prod

---

pubspec.lock
pubspec.yaml
rust/ecashapp/Cargo.lock
rust/ecashapp/Cargo.toml

Working towards https://github.com/fedimint/e-cash-app/issues/195

chore: bump version to v0.1.0-rc.1

---

lib/widgets/transaction_item.dart

Backport of https://github.com/fedimint/e-cash-app/pull/199

[Backport] fix: update label to Min Fee Rate

---

lib/frb_generated.dart
lib/multimint.dart
lib/multimint.freezed.dart
lib/screens/dashboard.dart
rust/ecashapp/src/frb_generated.rs
rust/ecashapp/src/multimint.rs
rust/ecashapp/src/nostr.rs

Backport of https://github.com/fedimint/e-cash-app/pull/206

[backport]: fix: update balance after zap

---

pubspec.yaml
rust/ecashapp/Cargo.lock
rust/ecashapp/Cargo.toml

Working towards https://github.com/fedimint/e-cash-app/issues/195

chore: bump version to v0.1.0-rc.2

---

lib/widgets/ln_address_dialog.dart

Fixes: https://github.com/fedimint/e-cash-app/issues/248

fix: prepend lightning: to LN Address QR Code

---

docs/release-process.md

Working towards https://github.com/fedimint/e-cash-app/issues/195
WIP release process docs while working through `v0.1.0` release

docs: add release process steps
